### ISSUE TITLE
STA9750 <GITHUB_USERNAME> MiniProject #01

### ISSUE THREAD

**Issue by annaol** [annaol/STA9750-2024-FALL#2]
Hi @michaelweylandt!

I've uploaded my work for MiniProject #01 - check it out!

https://annaol.github.io/STA9750-2024-FALL/mp01.html

**Comment by michaelweylandt** [comment]
Thanks @annaol !

Peer Feedback:

- @velasco23
- @fatima8808
- @katariasiddhi
- @aaronkcooper

It is now time for the peer feedback round for Mini-Project #01. Please
review @annaol's submission for this mini-project and provide peer feedback.

Using the rubric at https://michael-weylandt.com/STA9750/miniprojects/mini01.html#rubric,
please grade their submission out of a total of 50 points.

For each of the five categories, please give them a separate score and provide
a total (sum) score across the entire assignment. Feel free to assign extra
credit if you feel it is warranted (following the rubric).

If you give a score of less than 5 for any category, please provide a suggestion
for improvement. (You can also give suggestions for any element they did well -
more feedback is always great!)

As you go through this peer feedback exercise, think about what you particularly
like about this submission and how you can incorporate that approach in your future
work. If something is particularly insightful or creative, give some kudos!

Evaluators: This should take you around 15 minutes per peer feedback. You are
not required to engage in substantial back-and-forth with @annaol, but you are of course
welcome to initiate a discussion.

@annaol: please engage fully with your peers. They are here to help you!

Submission URL should be: https://annaol.github.io/STA9750-2024-FALL/mp01.html

Feel free to link to other repos, the course documentation, or other useful
examples.

Thanks!
@michaelweylandt

CC: @charles-ramirez

**Comment by fatima8808** [comment]
Hi @annaol, great work in completing your the first mini project of our course! I enjoyed the design and organization of your report and how clear you are in presenting the questions and answers required in our project. 

Written communication: 7
You did a nice job highlighting your key findings which helped the flow of your report overall. However, I think it would be insightful to see a little more context and explanation of your findings/what your findings might suggest. 

Project Skeleton: 10/10

Formatting & Display: 10/10 
I like how your tables are organized and easy to read, you also made sure to select columns most useful to the reader!

Code Quality: 10/10

Data Preparation: 10/10

Total Score: 47/50

**Comment by aaronkcooper** [comment]
Hi @annaol ,
Really nice job on the first Mini-Project! Here is my breakdown of feedback:
**Written Communication: 7/10**
I really liked the overall flow of the project, however the context behind each step was left quite sparse. I think there should be more informative motivation behind the code you present.

**Project Skeleton: 10/10**
All questions were answered as required.

**Formatting and Display: 9/10**
Tables were great and concise. I would have liked some more breaks between large blocks of code but otherwise it looks really nice. 

**Code Quality: 10/10**
Code is great, I found no issues here.

**Data Preparation: 10/10**

**Total Score: 46/50**
Great Job!

**Comment by katariasiddhi** [comment]
Hey @annaol,

Good job on finishing the project. I like the color scheme and consistency of the format throughout the website. The code is well organized, easy to follow, and has correct headers. Each question is broken down into sections and separated. Overall, the website and the code have been done really well. 

Written Communication: 9
Project Skeleton: 9
Formatting and Display: 9
Code Quality: 9
Data Preparation: 10
Total: 46

**Comment by charles-ramirez** [comment]
Hi @velasco23, 

This is just a reminder that your peer review is due today at 11:45 pm.

**Comment by velasco23** [comment]
hi @annaol I think you did a good job on your website. I appreciated the custom tables you created.

Written Communication - 7/10, my recommendation would be to describe what each task is asking instead of linking it. It made it difficult to follow by having to go to another link to remember what the task was asking for. 

Project Skeleton - 10/10 - great job no additional recommendations. 

Formatting & Display - 8/10 - custom tables made answers easier to read. To make it a 10 out of 10, In section "Additional Analysis of Transit Data" I would recommend separating all the questions with is perspective code. While I was reading it slowed me down having to read all the answers in one place then scrolling down to see the code.

Code Quality - 10/10 - no issues found

Data Preparation - 10/10

Overall: 45/50

**Comment by annaol** [comment]
Hi @fatima8808 @aaronkcooper @katariasiddhi @velasco23 

Thank you all so much for your very thoughtful feedback - I will be implementing a lot of it while revising the project. I did want to comment briefly on one specific suggestion regarding the adjustments to the Additional Analysis of Transit Data I received from @velasco23 .  In this section, I created a custom summary table which I used to draw insights on changes in transportation trends and I provided the code along with the note explaining that it produces the results discussed. I don't think I agree with the proposed change of separating all questions/insights with their respective code because that would result in repeating the same code block 4 times in a row.

Thanks again, everyone - I hope to see you again in other projects:)
