### ISSUE TITLE
STA/OPR 9750 <annaol> MiniProject #03

### ISSUE THREAD

**Issue by annaol** [annaol/STA9750-2024-FALL#4]
Hi @michaelweylandt!

https://annaol.github.io/STA9750-2024-FALL/mp03.html

**Comment by michaelweylandt** [comment]
Thanks @annaol !

Peer Feedback:

- @haolinnn
- @Cdiallo77
- @SethKauf
- @greazyz

It is now time for the peer feedback round for Mini-Project 03. Please
review @annaol's submission for this mini-project and provide peer feedback.

Using the rubric at https://michael-weylandt.com/STA9750/miniprojects/mini03.html#rubric,
please grade their submission out of a total of 50 points. Note that this
rubric is slightly different than that used for Mini-Projects 01 and 02.

For each of the five categories, please give them a separate score and provide
a total (sum) score across the entire assignment. Feel free to assign extra
credit if you feel it is warranted (following the rubric).

If you give a score of less than 5 for any category, please provide a suggestion
for improvement. (You can also give suggestions for any element they did well -
more feedback is always great!)

As you go through this peer feedback exercise, think about what you particularly
like about this submission and how you can incorporate that approach in your future
work. If something is particularly insightful or creative, give some kudos!

Evaluators: This should take you around 15 minutes per peer feedback. You are
not required to engage in substantial back-and-forth with @annaol, but you are of course
welcome to initiate a discussion.

@annaol: please engage fully with your peers. They are here to help you!

Submission URL should be: https://annaol.github.io/STA9750-2024-FALL/mp03.html

Feel free to link to other repos, the course documentation, or other useful
examples.

Thanks!
@michaelweylandt

CC: @charles-ramirez

**Comment by haolinnn** [comment]
Hi @annaol,

Written communication: 8/10
The report is good and flowed well following the instructions. But I think you could go into a little more detail in the introduction, or in the data section you could add an introduction or explanation about that data.

Project skeleton: 6/10
The tasks you completed are good, but task 7 is missing.

Format & display: 8/10
All tables and charts are properly labeled. I find the plot chart in task 3 question 3 interesting to visualize the results. It would be better if the maps could include state abbreviations.

Code quality: 10/10
Data preparation: 10/10
Data are clean. You use automated download appropriately, and the datasets are handled correctly according to the instructions.

Overall: 42/50

**Comment by SethKauf** [comment]
Hi @annaol,

Thank you for your project submission! Here are my notes.

Written Communication: 9/10
Good flow for the most part, I like how you present and your markdown is pretty clean

Project Skeleton: 6/10
As mentioned by a previous reviewer, you're missing Task 7 (I don't see it in the .qmd file either).

Formatting & Display: 6/10
I really liked everything up until Task 4. The maps especially leave a lot to be desired. I understand the struggle with the animated maps, but if you're going to print them out as you did, they need to be readable on the site without zooming in over 400%. Your Task 5 map is also labeled for 2020, not 2000. I do also think some of the tables should've been truncated especially on Task 3, and especially-especially because the Scatter Plot and Line Plot at the bottom of the Task do a much better job communicating the information than the datatables do.

Code quality: 10/10
Code seems well-commented and seems fine overall. I'm always a fan of importing libraries at the top of the file, my personal preference is to separate the `if (!require...)` statements from the `library()` statements, but I'm not going to dock points because of it

Data Preparation: 10/10
Data was cleaned and downloaded properly

Overall: 41/50

What I liked: The flow for the first-half of the project and the collapsible, commented code and the insight/analysis

What I didn't like: Missing Task 7, the maps need to be properly scaled/enlarged and labeled, lengthy datatables

**Comment by Cdiallo77** [comment]
Hello @annaol 


Written Communication: 10/10
Your communication was very clear and you provided ample explanation for each question.

Project Structure: 8.5/10
The objective is to answer all the question and you did deliver except task 7.  

Formatting & Display: 9/10
Graphs and visuals are good. Task 6 looks a bit funny. We all struggled with it, but I appreciate your effort. I will suggest you to make the map bigger . 

Code Quality: 10/10
The code line are well-organized and you commented each step. I still want to know how to hide the codes when I render. 

Data Preparation: 10/10

Overall:47.5/50

Great job!

**Comment by annaol** [comment]
hi @Cdiallo77 ,

Thank you so much for your feedback! 
This is what I do to fold code blocks in a markdown file- in each code chunk I want to display folded when it's rendered, I add 2 lines right after the opening tags, like so: 

{r echo=TRUE, warning=FALSE, message=FALSE}
#| code-fold: true   
#| code-summary: "Show the code" 

YOUR CODE HERE


You can also customize the text in code-summary line (where it says "Show the code").

Please let me know if this helps - and also feel free to reach out here and/or offline if you have any questions or need anything else.

Thanks again:)

**Comment by greazyz** [comment]
Hi Anna,
Written Communication 9: There is not much of a transition context between the prompts but the prompts are clearly labeled and completed.
Project Skeleton 9: Code completes tasks 1-6, missing task 7. All questions have a supporting graph or table.
Formatting and Display 10: The tables are clear and I like how you used tibbles to help support the results/code. 
Code Quality 10: Code runs without issues and comments are helpful.
Data Prep 10: Data import for congressional shapefiles is fully automated and efficient.

Total: 48/50

**Comment by Cdiallo77** [comment]
> hi @Cdiallo77 ,
> 
> Thank you so much for your feedback! This is what I do to fold code blocks in a markdown file- in each code chunk I want to display folded when it's rendered, I add 2 lines right after the opening tags, like so:
> 
> {r echo=TRUE, warning=FALSE, message=FALSE} #| code-fold: true #| code-summary: "Show the code"
> 
> YOUR CODE HERE
> 
> You can also customize the text in code-summary line (where it says "Show the code").
> 
> Please let me know if this helps - and also feel free to reach out here and/or offline if you have any questions or need anything else.
> 
> Thanks again:)

Hi @annaol 
thank you for the code, this will definitely improve my last project.
